package rafafrench;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sena
 */
public class VistaPlatos extends javax.swing.JFrame {

    Plato obj = new Plato();
    String est;

    /**
     * Creates new form Platos
     */
    public VistaPlatos() {
        initComponents();
        //Obtenemos la fecha
        java.util.Date fecha = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        txtFecha.setText(sdf.format(fecha));
        lblfechaIngreso.setText(sdf.format(fecha));
        lblfechaIngreso.setForeground(Color.decode("#faf6f5"));
        txtcodigo.requestFocus();
        //SE ESTABLECE EL ESTADO PREDETERMINADO
        txtestado.setHorizontalAlignment(JTextField.CENTER);
        txtestado.setText("Activo");
        txtestado.setForeground(Color.decode("#10ba20"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRbtn = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        lblfechaIngreso = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCosultar = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        lblestado = new javax.swing.JLabel();
        lblventa = new javax.swing.JLabel();
        txtVenta = new javax.swing.JTextField();
        lblcosto = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        lblfecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        lblnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        txtestado = new javax.swing.JTextField();
        lblcodigo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 234, 234));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLATO");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(210, 10, 87, 30);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 153, 255));
        btnSalir.setText("SALIR");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jDesktopPane1.add(btnSalir);
        btnSalir.setBounds(430, 0, 80, 40);

        lblfechaIngreso.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblfechaIngreso.setText("Fecha");
        jDesktopPane1.add(lblfechaIngreso);
        lblfechaIngreso.setBounds(10, 10, 120, 18);

        jPanel2.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 40));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 153, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, 30));

        btnCosultar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCosultar.setForeground(new java.awt.Color(0, 153, 255));
        btnCosultar.setText("CONSULTAR");
        btnCosultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCosultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosultarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCosultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 100, 30));

        btnEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEstado.setForeground(new java.awt.Color(0, 153, 255));
        btnEstado.setText("INHABILITAR");
        btnEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 110, 30));

        lblestado.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblestado.setText("ESTADO");
        jPanel2.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        lblventa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblventa.setText("PRECIO VENTA");
        jPanel2.add(lblventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        txtVenta.setBackground(new java.awt.Color(204, 204, 255));
        txtVenta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVentaFocusLost(evt);
            }
        });
        jPanel2.add(txtVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, -1));

        lblcosto.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblcosto.setText("COSTO");
        jPanel2.add(lblcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtCosto.setBackground(new java.awt.Color(204, 204, 255));
        txtCosto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 170, -1));

        lblfecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblfecha.setText("FECHA DE INGRESO");
        jPanel2.add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 170, -1));

        lblnombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblnombre.setText("NOMBRE");
        jPanel2.add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtnombre.setBackground(new java.awt.Color(204, 204, 255));
        txtnombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 170, -1));

        txtcodigo.setBackground(new java.awt.Color(204, 204, 255));
        txtcodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigoKeyReleased(evt);
            }
        });
        jPanel2.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 170, -1));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 153, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, 30));

        txtestado.setEditable(false);
        txtestado.setBackground(new java.awt.Color(204, 204, 255));
        txtestado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txtestado.setRequestFocusEnabled(false);
        txtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtestadoActionPerformed(evt);
            }
        });
        txtestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtestadoKeyReleased(evt);
            }
        });
        jPanel2.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 170, -1));

        lblcodigo1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblcodigo1.setText("CODIGO");
        jPanel2.add(lblcodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //Activo/Inactivo
        int confir=-1;

        if (!"".equals(txtcodigo.getText()) && !"".equals(txtnombre.getText()) && !"".equals(txtCosto.getText()) && !"".equals(txtVenta.getText())) {
            int pos = -1;
            pos = obj.existe(Integer.parseInt(txtcodigo.getText()));
            if (pos > -1) {
                // Existe el codigo
                colocar();
                confir = JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios realizados a este plato?", "Verificacion", JOptionPane.YES_NO_OPTION);
                System.out.println(confir);
                if (confir == JOptionPane.YES_OPTION) {
                    //CONFIRMAMOS SI REALMENTE DESEA MODIFICAR EL REGISTRO
                    if (obj.actualizar(pos)) {
                        JOptionPane.showMessageDialog(null, "Registro actualizado");
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo actualizar el registro, por favor intentelo nuevamente");
                    }
                }

            } else {
                //No existe el codigo el plato

                //Verificamos si ya hay un plato con este nombre
                if (obj.existe(txtnombre.getText())) {
                    JOptionPane.showMessageDialog(null, "No se puede guardar el Plato, nombre existente.");
                    txtnombre.requestFocus();
                } else {
                    obj = new Plato(Integer.parseInt(txtcodigo.getText()), txtnombre.getText(), txtFecha.getText(), Integer.parseInt(txtCosto.getText()), Integer.parseInt(txtVenta.getText()), "Activo");
                    if (obj.agregar()) {
                        JOptionPane.showMessageDialog(null, "Plato agregado");
                        limpiar();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo agregar el plato, por favor vuelva a intentarlo");
                    }

                }

            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtcodigo.getText())) {
                Plato p1 = new Plato();
                try {
                    p1 = obj.consultar(Integer.parseInt(txtcodigo.getText()));
                    if (p1.getCodigo() > 0) {
                        txtnombre.setText(p1.getNombre());
                        txtFecha.setText(p1.getFecha());
                        txtCosto.setText(String.valueOf(p1.getVal_costo()));
                        txtVenta.setText(String.valueOf(p1.getVal_venta()));
                        txtestado.setText(p1.getEstado());
                        if (txtestado.getText().equals("Activo")) {
                            txtestado.setForeground(Color.decode("#10ba20"));
                        } else {
                            txtestado.setForeground(Color.decode("#a81d07"));
                        }
                    } else {
                        limpiar2();
                    }
                } catch (Exception ex) {
                    System.out.println("Error al consultar \n" + ex.getMessage());
                }
            } else {
                System.out.println("entro......");
                limpiar2();
            }

        }
    }//GEN-LAST:event_txtcodigoKeyReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVentaFocusLost
        // TODO add your handling code here:
        if (Integer.parseInt(txtCosto.getText()) > Integer.parseInt(txtVenta.getText())) {
            JOptionPane.showMessageDialog(null, "El precio de la venta no puede ser inferior al costo");
            txtVenta.requestFocus();
        } else if (Integer.parseInt(txtCosto.getText()) == Integer.parseInt(txtVenta.getText())) {
            JOptionPane.showMessageDialog(null, "El precio de la venta no puede igual al costo");
            txtVenta.requestFocus();
        }
    }//GEN-LAST:event_txtVentaFocusLost

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoActionPerformed

    private void txtestadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtestadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtestadoKeyReleased

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        if (txtestado.getText().equals("Activo")) {
            txtestado.setText("Inactivo");
            txtestado.setForeground(Color.decode("#a81d07"));
            btnEstado.setText("Habilitar");
            btnEstado.setSize(110, 30);
        } else if (txtestado.getText().equals("Inactivo")) {
            txtestado.setText("Activo");
            txtestado.setForeground(Color.decode("#10ba20"));
            btnEstado.setText("Inhabilitar");
        }
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnCosultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosultarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtcodigo.getText())) {
            Plato p1 = new Plato();
            try {
                p1 = obj.consultar(Integer.parseInt(txtcodigo.getText()));
                if (p1.getCodigo() > 0) {
                    txtnombre.setText(p1.getNombre());
                    txtFecha.setText(p1.getFecha());
                    txtCosto.setText(String.valueOf(p1.getVal_costo()));
                    txtVenta.setText(String.valueOf(p1.getVal_venta()));
                    txtestado.setText(p1.getEstado());
                    if (txtestado.getText().equals("Activo")) {
                        txtestado.setForeground(Color.decode("#10ba20"));
                    } else {
                        txtestado.setForeground(Color.decode("#a81d07"));
                    }
                } else {
                    limpiar2();
                }
            } catch (Exception ex) {
                System.out.println("Error al consultar \n" + ex.getMessage());
            }
        } else {
            System.out.println("entro......");
            limpiar2();
        }


    }//GEN-LAST:event_btnCosultarActionPerformed

    public void colocar() {
        obj.setCodigo(Integer.parseInt(txtcodigo.getText()));
        obj.setNombre(txtnombre.getText());
        obj.setFecha(txtFecha.getText());
        obj.setVal_costo(Integer.parseInt(txtCosto.getText()));
        obj.setVal_venta(Integer.parseInt(txtVenta.getText()));
        obj.setEstado(txtestado.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPlatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPlatos().setVisible(true);
            }
        });
    }

    public void limpiar() {

        txtcodigo.setText(null);
        txtnombre.setText(null);
        txtCosto.setText(null);
        txtVenta.setText(null);
        txtestado.setText("Activo");
        txtestado.setForeground(Color.decode("#10ba20"));
        txtcodigo.requestFocus();
    }

    public void limpiar2() {
        txtcodigo.requestFocus();
        txtnombre.setText(null);
        txtCosto.setText(null);
        txtVenta.setText(null);
        txtestado.setText("Activo");
        txtestado.setForeground(Color.decode("#10ba20"));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCosultar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup grupoRbtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcosto;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblfechaIngreso;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblventa;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtVenta;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
